#pragma once

/*----------------------------------------------------------------------
 * Purpose:
 *		Cfix auxilliary header file - defines structures used for
 *		PE-based test modules. Do not include directly - 
 *		include either cfixapi.h or cfix.h.
 *
 *		Note: Test code should include cfix.h.
 *
 *            cfixaux.h
 *              ^ ^
 *             /   \
 *            /     \
 *		cfixapi.h  cfixpe.h
 *			^	  ^	 ^
 *			|	 /	  \
 *			|	/	   \
 *		  [Impl]	 cfix.h
 *
 * Copyright:
 *		2008, Johannes Passing (passing at users.sourceforge.net)
 *
 * This file is part of cfix.
 *
 * cfix is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * cfix is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with cfix.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <cfixaux.h>

/*----------------------------------------------------------------------
 *
 * Definitions for test map.
 *
 * Sampe usage:
 * 
 * CFIX_BEGIN_FIXTURE(Ts01)
 * 	CFIX_FIXTURE_SETUP(Setup)
 * 	CFIX_FIXTURE_TEARDOWN(Tdown)
 * 	CFIX_FIXTURE_ENTRY(TcFunc1)
 * 	CFIX_FIXTURE_ENTRY(TcFunc2)
 * CFIX_END_FIXTURE()
 *
 */
typedef enum
{
	CfixEntryTypeEnd			= 0,
	CfixEntryTypeSetup		= 1,
	CfixEntryTypeTeardown		= 2,
	CfixEntryTypeTestcase		= 3
} CFIX_ENTRY_TYPE;


/*++
	Description:
		Prototype of setup, teardown and testcase routines.
--*/
typedef VOID ( CALLBACK * CFIX_PE_TESTCASE_ROUTINE )();

/*++
	Struct Description:
		Defines an entry in a test map. Only used by
		CFIX_GET_FIXTURE_ROUTINE-routines.
--*/
typedef struct _CFIX_PE_DEFINITION_ENTRY
{
	CFIX_ENTRY_TYPE Type;
	PCWSTR Name;
	CFIX_PE_TESTCASE_ROUTINE Routine;
} CFIX_PE_DEFINITION_ENTRY, *PCFIX_PE_DEFINITION_ENTRY;

/*++
	Struct Description:
		Defines a test map. Only used by
		CFIX_GET_FIXTURE_ROUTINE-routines.
--*/
typedef struct _CFIX_TEST_PE_DEFINITION
{
	DWORD ApiVersion;
	PCFIX_PE_DEFINITION_ENTRY Entries;
} CFIX_TEST_PE_DEFINITION, *PCFIX_TEST_PE_DEFINITION;

/*++
	Description:
		Prototype of export of test DLL that is generated by test map.
--*/
typedef PCFIX_TEST_PE_DEFINITION ( CFIXCALLTYPE * CFIX_GET_FIXTURE_ROUTINE )();


#define CFIX_PE_API_VERSION	MAKELONG( 1, 0 )

#define CFIX_BEGIN_FIXTURE(name)											\
EXTERN_C __declspec(dllexport)										\
PCFIX_TEST_PE_DEFINITION CFIXCALLTYPE __CfixFixturePe##name()		\
{																	\
	static CFIX_PE_DEFINITION_ENTRY Entries[] = {					\

#define CFIX_FIXTURE_SETUP(func)											\
	{ CfixEntryTypeSetup, __CFIX_WIDE( #func ), func },								

#define CFIX_FIXTURE_TEARDOWN(func)										\
	{ CfixEntryTypeTeardown,__CFIX_WIDE( #func ), func },								

#define CFIX_FIXTURE_ENTRY(func)											\
	{ CfixEntryTypeTestcase, __CFIX_WIDE( #func ), func },								

#define CFIX_END_FIXTURE()												\
	{ CfixEntryTypeEnd, NULL, NULL }								\
	};																\
	static CFIX_TEST_PE_DEFINITION Fixture = {						\
		CFIX_PE_API_VERSION,										\
		Entries														\
	};																\
	return &Fixture;												\
}			
